package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// envDir returns ~/.mcp-server-envs path.
func envDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".mcp-server-envs")
}

// WriteAtlassianEnv writes Atlassian environment file.
func WriteAtlassianEnv(cfg *AtlassianConfig) error {
	var sb strings.Builder
	sb.WriteString("# Atlassian MCP Server - generated by mcp-toolkit\n\n")
	sb.WriteString(fmt.Sprintf("CONFLUENCE_URL=%s/wiki\n", cfg.URL))
	sb.WriteString(fmt.Sprintf("CONFLUENCE_USERNAME=%s\n", cfg.Email))
	sb.WriteString(fmt.Sprintf("CONFLUENCE_API_TOKEN=%s\n", cfg.APIToken))
	sb.WriteString(fmt.Sprintf("JIRA_URL=%s\n", cfg.URL))
	sb.WriteString(fmt.Sprintf("JIRA_USERNAME=%s\n", cfg.Email))
	sb.WriteString(fmt.Sprintf("JIRA_API_TOKEN=%s\n", cfg.APIToken))
	if cfg.JiraProjects != "" {
		sb.WriteString(fmt.Sprintf("JIRA_PROJECTS_FILTER=%s\n", cfg.JiraProjects))
	}
	readOnly := "false"
	if cfg.ReadOnly {
		readOnly = "true"
	}
	sb.WriteString(fmt.Sprintf("READ_ONLY_MODE=%s\n", readOnly))
	return os.WriteFile(filepath.Join(envDir(), ".mcp-atlassian.env"), []byte(sb.String()), 0600)
}

func vaultEnvPath() string {
	return filepath.Join(envDir(), ".mcp-vault.env")
}

func vaultWrapperPath() string {
	return filepath.Join(envDir(), "vault-mcp-wrapper.sh")
}

// WriteVaultEnv writes Vault environment file.
func WriteVaultEnv(cfg *VaultConfig) error {
	var sb strings.Builder
	sb.WriteString("# Vault MCP Server - generated by mcp-toolkit\n\n")
	sb.WriteString(fmt.Sprintf("VAULT_ADDR=%s\n", cfg.Address))
	sb.WriteString(fmt.Sprintf("VAULT_TOKEN=%s\n", cfg.Token))
	if cfg.Namespace != "" {
		sb.WriteString(fmt.Sprintf("VAULT_NAMESPACE=%s\n", cfg.Namespace))
	}
	return os.WriteFile(vaultEnvPath(), []byte(sb.String()), 0600)
}

// WriteVaultWrapper writes Vault wrapper script.
func WriteVaultWrapper(cfg *VaultConfig) error {
	envPath := vaultEnvPath()
	script := fmt.Sprintf(`#!/bin/bash
# Vault MCP wrapper - generated by mcp-toolkit
if [ -f "%s" ]; then
    export $(grep -v '^#' "%s" | xargs)
fi
exec %s "$@"
`, envPath, envPath, cfg.BinaryPath)
	return os.WriteFile(vaultWrapperPath(), []byte(script), 0700)
}

// WriteKubernetesEnv writes Kubernetes environment file.
func WriteKubernetesEnv(_ *KubernetesConfig) error {
	var sb strings.Builder
	sb.WriteString("# Kubernetes MCP Server - generated by mcp-toolkit\n\n")
	sb.WriteString("# Kubernetes uses ~/.kube/config by default\n")
	sb.WriteString("# Set KUBECONFIG to override the default path\n")
	return os.WriteFile(filepath.Join(envDir(), ".mcp-kubernetes.env"), []byte(sb.String()), 0600)
}

// WriteGitHubEnv writes GitHub environment file.
func WriteGitHubEnv(_ *GitHubConfig) error {
	var sb strings.Builder
	sb.WriteString("# GitHub MCP Server - generated by mcp-toolkit\n\n")
	sb.WriteString("# GitHub Copilot uses its own authentication\n")
	sb.WriteString("# No additional configuration needed\n")
	return os.WriteFile(filepath.Join(envDir(), ".mcp-github.env"), []byte(sb.String()), 0600)
}

// WriteSupabaseEnv writes Supabase environment file.
func WriteSupabaseEnv(cfg *SupabaseConfig) error {
	var sb strings.Builder
	sb.WriteString("# Supabase MCP Server - generated by mcp-toolkit\n\n")
	sb.WriteString(fmt.Sprintf("SUPABASE_PROJECT_REF=%s\n", cfg.ProjectRef))
	return os.WriteFile(filepath.Join(envDir(), ".mcp-supabase.env"), []byte(sb.String()), 0600)
}
